// Auto-gerado — NCMs 3002/3004 com múltiplos enquadramentos fiscais em constants.js

export const NCM_SUBSTANCES_MAP = {
  "30021211": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","SORO ANTIARACNÍDICO (LOXOSCELES, PHONEUTRIA E TITYUS)","SORO ANTIBOTRÓPICO (PENTAVALENTE)","SORO ANTIBOTRÓPICO (PENTAVALENTE) E ANTICROTÁLICO","SORO ANTIBOTRÓPICO (PENTAVALENTE) E ANTILAQUÉTICO","SORO ANTICROTÁLICO","SORO ANTIELAPÍDICO (BIVALENTE)","SORO ANTIESCORPIÔNICO","SORO ANTILONÔMICO","SORO ANTILOXOSCÉLICO (TRIVALENTE)"],
  "30021212": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","SORO ANTITETÂNICO"],
  "30021215": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","SORO ANTIDIFTÉRICO"],
  "30021219": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","SORO ANTIBOTULÍNICO AB (BIVALENTE)","SORO ANTIRRÁBICO"],
  "30021221": ["Imunoglobulina anti-Rh","Outras frações do sangue, exceto as preparadas como medicamentos, as imunoglobulinas séric","Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos"],
  "30021222": ["Outras imunoglobulinas séricas","Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos"],
  "30021223": ["Concentrado de fator VIII","Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos"],
  "30021229": ["Outras frações do sangue, exceto as preparadas como medicamentos, as imunoglobulinas séric","Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos"],
  "30021236": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","Albumina humana"],
  "30021239": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ALBUMINA HUMANA","ALFAEPOETINA","BETAEPOETINA","COMPLEXO PROTROMBÍNICO PARCIALMENTE ATIVADO","FATOR IX DE COAGULAÇÃO","FATOR VII DE COAGULAÇÃO ATIVADO RECOMBINANTE","FATOR VIII DE COAGULAÇÃO","FATOR VIII DE COAGULAÇÃO CONTENDO FATOR DE VON WILLEBRAND","FATOR VIII DE COAGULAÇÃO RECOMBINANTE","IMUNOGLOBULINA ANTIRRÁBICA","IMUNOGLOBULINA ANTITETÂNICA","IMUNOGLOBULINA HUMANA ANTI-HEPATITE B"],
  "30021510": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ALFAPEGINTERFERONA 2A","PEG INTERFERON ALFA-2A"],
  "30021520": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","BEVACIZUMABE","RITUXIMABE","TRASTUZUMABE"],
  "30021590": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","AFLIBERCEPTE","ALBINTERFERONA ALFA-2B","ALENTUZUMABE","ALFAINTERFERONA","ALFAPEGINTERFERONA 2B","ATEZOLIZUMABE","AVELUMABE","BLINATUMOMABE","BRENTUXIMABE VEDOTINA","CETUXIMABE","DARATUMUMABE","DENOSUMABE","DURVALUMABE","ECULIZUMABE","ELOTUZUMABE","EMICIZUMABE","FILGRASTIM","GOLIMUMABE","INTERFERON ALFA-2A E INTERFERON ALFA-2B","IPILIMUMABE","LIPEGFILGRASTIM","MEPOLIZUMABE","NIVOLUMABE","OCRELIZUMABE","OLARATUMABE","PANITUMUMABE","PEG INTERFERON ALFA-2B","PEGFILGRASTIM","PERTUZUMABE","RAMUCIRUMABE","RISANQUIZUMABE","SECUQUINUMABE","TOCILIZUMABE","VEDOLIZUMABE"],
  "30024122": ["VACINA POLIOMIELITE 1 E 3 (ATENUADA)","VACINA POLIOMIELITE 1, 2 E 3 (INATIVADA)"],
  "30024125": ["VACINA MENINGOCÓCICA ACWY (CONJUGADA)","VACINA MENINGOCÓCICA C (CONJUGADA)"],
  "30024127": ["VACINA ADSORVIDA DIFTERIA, TÉTANO E PERTUSSIS","VACINA ADSORVIDA DIFTERIA, TÉTANO E PERTUSSIS (ACELULAR)","VACINA SARAMPO, CAXUMBA, RUBÉOLA"],
  "30024129": ["VACINA ADSORVIDA DIFTERIA E TÉTANO","VACINA ADSORVIDA DIFTERIA, TÉTANO, PERTUSSIS, HEPATITE B (RECOMBINANTE) E HAEMOPHILUS INFL","VACINA ADSORVIDA HEPATITE A (INATIVADA)","VACINA BCG","VACINA CÓLERA (INATIVADA)","VACINA COVID-19","VACINA DENGUE 1, 2, 3 E 4","VACINA FEBRE AMARELA (ATENUADA)","VACINA FEBRE TIFÓIDE (POLISSACARÍDICA)","VACINA HAEMOPHILUS INFLUENZAE B (CONJUGADA)","VACINA PAPILOMAVÍRUS HUMANO 6, 11, 16 E 18 (RECOMBINANTE)","VACINA PNEUMOCÓCICA 10-VALENTE (CONJUGADA)","VACINA PNEUMOCÓCICA 13-VALENTE (CONJUGADA)","VACINA PNEUMOCÓCICA 23-VALENTE (POLISSACARÍDICA)","VACINA RAIVA (INATIVADA)","VACINA ROTAVÍRUS HUMANO G1P 8 (ATENUADA)","VACINA SARAMPO, CAXUMBA, RUBÉOLA E VARICELA (ATENUADA)","VACINA VARICELA (ATENUADA)"],
  "30029000": ["Inoculantes, meios de cultura e outros microorganismos para uso agrícola; em conformidade ","Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ONASEMNOGENO ABEPARVOVEQUE"],
  "30042032": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","RIFAMPICINA + ISONIAZIDA"],
  "30042059": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CEFALOTINA","CEFOXITINA","CEFTAZIDIMA"],
  "30042063": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","IDARRUBICINA"],
  "30042069": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CLORIDRATO DE DAUNORRUBICINA","CLORIDRATO DE DOXORRUBICINA","CLORIDRATO DE IDARRUBICINA"],
  "30042071": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","VANCOMICINA"],
  "30042091": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","MITOMICINA"],
  "30042093": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","SULFATO DE BLEOMICINA"],
  "30042094": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CILASTATINA SÓDICA + IMIPENEM"],
  "30042095": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ANFOTERICINA B EM LIPOSSOMAS"],
  "30042099": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ANFOTERICINA B","CLORIDRATO DE EPIRRUBICINA","DOXICICLINA MONOIDRATADA","TETRACICLINA"],
  "30043100": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","INSULINA GLARGINA","INSULINA HUMANA"],
  "30043210": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACEPONATO DE METILPREDNISOLONA","PREDNISOLONA","SUCCINATO SÓDICO DE HIDROCORTISONA"],
  "30043220": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ESPIRONOLACTONA"],
  "30043290": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACETATO DE ABIRATERONA","DEXAMETASONA"],
  "30043918": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACETATO DE TRIPTORRELINA","EMBONATO DE TRIPTORRELINA","TRIPTORRELINA"],
  "30043919": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACETATO DE LEUPRORRELINA"],
  "30043926": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","OCTREOTIDA"],
  "30043927": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACETATO DE GOSSERRELINA","GOSSERRELINA"],
  "30043929": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACETATO DE DEGARELIX","ACETATO DE OCTREOTIDA","ACETATO DESMOPRESSINA","ALFATIROTROPINA","DIASPARTATO DE PASIREOTIDA","PAMOATO DE PASIREOTIDA","SOMATROPINA"],
  "30043936": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACETATO DE MEGESTROL","FULVESTRANTO"],
  "30043939": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACETATO DE CIPROTERONA","ETINILESTRADIOL + LEVONORGESTREL"],
  "30043994": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","EXEMESTANO"],
  "30043999": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","BUDESONIDA"],
  "30044910": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CLORIDRATO DE TOPOTECANA","SULFATO DE VINCRISTINA","VIMBLASTINA","VINCRISTINA"],
  "30044950": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","GRANISETRON"],
  "30044990": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","BROMETO DE IPRATRÓPIO","CLORIDRATO DE GRANISSETRONA","CLORIDRATO DE IRINOTECANO","CLORIDRATO DE IRINOTECANO TRI-HIDRATADO","DICLORIDRATO DE QUININA","DITARTARATO DE VINORELBINA","QUININA","SULFATO DE MORFINA","SULFATO DE MORFINA PENTAIDRATADO","SULFATO DE QUININA","TARTARATO DE VINORELBINA","VINORELBINA"],
  "30045010": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","FOLINATO DE CÁLCIO"],
  "30045090": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ÁCIDO FOLÍNICO (FÓLICO)","CLORIDRATO DE PIRIDOXINA","ISOTRETINOÍNA"],
  "30046000": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ARTEMÉTER","ARTEMÉTER + LUMEFANTRINA","ARTESUNATO + CLORIDRATO MEFLOQUINA","ARTESUNATO DE SÓDIO"],
  "30049012": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ASPARAGINASE"],
  "30049014": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","IDURSULFASE"],
  "30049019": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ALFA-ALGLICOSIDASE","ALFAELOSULFASE","ALFAVESTRONIDASE","ALTEPLASE","GALSULFASE","PANCREATINA","PEGASPARGASE","RASBURICASE","TENECTEPLASE"],
  "30049029": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ACITRETINA","ANTIMONIAL PENTAVALENTE","FUMARATO DE DIMETILA"],
  "30049034": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CITRATO DE TAMOXIFENO","TAMOXIFENO"],
  "30049035": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CARBIDOPA + LEVODOPA"],
  "30049038": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CLORAMBUCILA"],
  "30049039": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ÁCIDO TRANEXÂMICO","CLORIDRATO DE AMINOLEVULINATO DE METILA","CLORIDRATO DE CINACALCETE","CLORIDRATO DE DOBUTAMINA","CLORIDRATO DE FINGOLIMODE","CLORIDRATO DE MITOXANTRONA","MESILATO DE RASAGILINA","PREGABALINA","SUCCINATO DE METOPROLOL"],
  "30049041": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CLORIDRATO DE METOCLOPRAMIDA"],
  "30049042": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ATENOLOL"],
  "30049043": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","LIDOCAÍNA"],
  "30049047": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ISETIONATO DE PENTAMIDINA"],
  "30049048": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CARMUSTINA","MESILATO DE DESFERROXAMINA"],
  "30049049": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","FOSFATO DE OSELTAMIVIR","MARAVIROQUE","RALTEGRAVIR","TERIFLUNOMIDA"],
  "30049058": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CLODRONATO DISSÓDICO","FOTEMUSTINA"],
  "30049059": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ALENDRONATO DE SÓDIO","AMIFOSTINA","BICALUTAMIDA","CABAZITAXEL","CITRATO DE IXAZOMIBE","DAPAGLIFLOZINA","DOCETAXEL","DOCETAXEL TRI-HIDRATADO","IBANDRONATO SÓDIO","MESNA","MICOFENOLATO DE SÓDIO","MIFAMURTIDA","PACLITAXEL","PAMIDRONATO DISSÓDICO","SINVASTATINA"],
  "30049063": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","MERCAPTOPURINA","PRAZIQUANTEL"],
  "30049064": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","DIAZEPAM"],
  "30049066": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","AZATIOPRINA"],
  "30049068": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","BORTEZOMIBE","CLORIDRATO DE ERLOTINIBE","DACARBAZINA","ENFUVIRTIDA","FUMARATO DE TENOFOVIR DESOPROXILA","LETROZOL","LOPINAVIR + RITONAVIR","MESILATO DE IMATINIBE","MESILATO DE NELFINAVIR","NEVIRAPINA","SAQUINAVIR","SULFATO DE ABACAVIR","SULFATO DE ATAZANAVIR","SULFATO DE INDINAVIR","TEMOZOLOMIDA","TENOFOVIR","TIOGUANINA","ZIAGENAVIR"],
  "30049069": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ABACAVIR","ABEMACICLIBE","ACALABRUTINIBE","ÁCIDO ZOLEDRÔNICO","ANASTROZOL","APALUTAMIDA","AXITINIBE","BENZONIDAZOL","BESILATO DE ANLODIPINO","BRIGATINIBE","CLOFAZIMINA","CLORIDRATO DE ALFENTANILA MONOIDRATADA","CLORIDRATO DE PALONOSETRONA","CLORIDRATO DE PONATINIBE","CRIZOTINIBE","DAROLUTAMIDA","DEFERASIROX","DICLORIDRATO DE DACLATASVIR","DICLORIDRATO DE SAPROPTERINA","DIFOSFATO DE CLOROQUINA","DIMETILSULFÓXIDO DE TRAMETINIBE","ELEXACAFTOR","ELTROMBOPAGUE OLAMINA","ENZALUTAMIDA","ERDAFITINIBE","ESILATO DE NINTEDANIBE","ETOMIDATO","ETRAVIRINA","FENTANILA","FLUORURACILA","FOSFATO DE RUXOLITINIBE","FOSFATO DE SITAGLIPTINA","GANCICLOVIR SÓDICO","HALOPERIDOL","IBRUTINIBE","IVACAFTOR","LEVETIRACETAM","LOSARTANA POTÁSSICA","LUMACAFTOR","MALEATO DE ACALABRUTINIBE MONOIDRATADO","MALEATO DE SUNITINIBE","MESILATO DE OSIMERTINIBE","METOTREXATO","METOTREXATO DE SÓDIO","MIDAZOLAM","NILOTINIBE","NITRENDIPINO","OLAPARIBE","PALBOCICLIBE","PEMETREXEDE DISSÓDICO","PEMETREXEDE DISSÓDICO HEMIPENTAIDRATADO","PEMETREXEDE DISSÓDICO HEPTAIDRATADO","PLERIXAFOR","RABEPRAZOL SÓDICO","REGORAFENIBE","RILUZOL","RISDIPLAM","RISPERIDONA","SACUBITRIL VALSARTANA SÓDICA HIDRATADA","SAXAGLIPTINA","SUCCINATO DE RIBOCICLIBE","SULFATO DE LAROTRECTINIBE","TARTARATO DE VARENICLINA","TEZACAFTOR","TOSILATO DE SORAFENIBE","UPADACITINIBE HEMI-HIDRATADO","VANDETANIBE"],
  "30049072": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","SULFADIAZINA","SULFAMETOXAZOL + TRIMETROPINA"],
  "30049076": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","FUROSEMIDA"],
  "30049078": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","APREPITANTO","CLORIDRATO DE GENCITABINA","EFAVIRENZ","EMTRICITABINA","ENTRICITABINA","ENTRICITABINA + FUMARATO TENOFOVIR DESOPROXILA","ETOPOSIDEO","EVEROLIMO","FOSAMPRENAVIR CÁLCICO","FOSFATO DE FLUDARABINA","RITONAVIR","TACROLIMO","TENIPOSIDEO","TENSIROLIMO","TIPRANAVIR"],
  "30049079": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","ALPELISIBE","AMBRISENTANA","AZACITIDINA","BARICITINIBE","CAPECITABINA","CARFILZOMIBE","CELECOXIBE","CICLOFOSFAMIDA","CITARABINA","CLADRIBINA","CLORIDRATO DE ALECTINIBE","CLORIDRATO DE PAZOPANIBE","CLORIDRATO DE ZIPRASIDONA MONOIDRATADO","DASATINIBE","DECITABINA","DICLORIDRATO DE PRAMIPEXOL MONOIDRATADO","DIDANOSINA","DIMALEATO DE AFATINIBE","DOLUTEGRAVIR SÓDICO","ESTAVUDINA","GEFITINIBE","IFOSFAMIDA","LAMIVUDINA + ZIDOVUDINA","LINEZOLIDA","MALEATO DE TIMOLOL","MESILATO DE DABRAFENIBE","MICOFENOLATO DE MOFETILA","MIDOSTAURINA","NUSINERSENA","PIOGLITAZONA","RIBAVIRINA","SELEXIPAGUE","SOFOSBUVIR","TAFAMIDIS MEGLUMINA","TERIZIDONA","VINFLUNINA","ZIDOVUDINA"],
  "30049095": ["Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","BUSSULFANO","DIETILESTILBESTROL","MITOTANO","PROPOFOL"],
  "30049099": ["Substitutos de enxerto ósseo","Conjuntos de troca e concentrados polieletrolíticos para diálise","Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos","CARBOPLATINA","CISPLATINA","CLORETO DE SUXAMETÔNIO","ENFLURANO","GLICOSE","HIDROXIUREIA","HIPOCLORITO DE SÓDIO","ISOFLURANO","METILPREDNISOLONA","OXALIPLATINA","TRIÓXIDO DE ARSÊNIO"],
};

export const NCM_SUBSTANCES_FULL = {
  "30021211": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "SORO ANTIARACNÍDICO (LOXOSCELES, PHONEUTRIA E TITYUS)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTIBOTRÓPICO (PENTAVALENTE)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTIBOTRÓPICO (PENTAVALENTE) E ANTICROTÁLICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTIBOTRÓPICO (PENTAVALENTE) E ANTILAQUÉTICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTICROTÁLICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTIELAPÍDICO (BIVALENTE)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTIESCORPIÔNICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTILONÔMICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTILOXOSCÉLICO (TRIVALENTE)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30021212": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "SORO ANTITETÂNICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30021215": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "SORO ANTIDIFTÉRICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30021219": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "SORO ANTIBOTULÍNICO AB (BIVALENTE)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SORO ANTIRRÁBICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30021221": [
    { desc: "Imunoglobulina anti-Rh", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IV da LC 214/2025" },
    { desc: "Outras frações do sangue, exceto as preparadas como medicamentos, as imunoglobulinas séric", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IV da LC 214/2025" },
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
  ],
  "30021222": [
    { desc: "Outras imunoglobulinas séricas", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IV da LC 214/2025" },
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
  ],
  "30021223": [
    { desc: "Concentrado de fator VIII", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IV da LC 214/2025" },
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
  ],
  "30021229": [
    { desc: "Outras frações do sangue, exceto as preparadas como medicamentos, as imunoglobulinas séric", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IV da LC 214/2025" },
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
  ],
  "30021236": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "Albumina humana", reducao: 60, tipo: "Red. 60%", anexo: "Anexo V da LC 214/2025" },
  ],
  "30021239": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ALBUMINA HUMANA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALFAEPOETINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "BETAEPOETINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "COMPLEXO PROTROMBÍNICO PARCIALMENTE ATIVADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FATOR IX DE COAGULAÇÃO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FATOR VII DE COAGULAÇÃO ATIVADO RECOMBINANTE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FATOR VIII DE COAGULAÇÃO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FATOR VIII DE COAGULAÇÃO CONTENDO FATOR DE VON WILLEBRAND", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FATOR VIII DE COAGULAÇÃO RECOMBINANTE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "IMUNOGLOBULINA ANTIRRÁBICA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "IMUNOGLOBULINA ANTITETÂNICA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "IMUNOGLOBULINA HUMANA ANTI-HEPATITE B", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30021510": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ALFAPEGINTERFERONA 2A", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PEG INTERFERON ALFA-2A", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30021520": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "BEVACIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RITUXIMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TRASTUZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30021590": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "AFLIBERCEPTE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALBINTERFERONA ALFA-2B", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALENTUZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALFAINTERFERONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALFAPEGINTERFERONA 2B", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ATEZOLIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "AVELUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "BLINATUMOMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "BRENTUXIMABE VEDOTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CETUXIMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DARATUMUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DENOSUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DURVALUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ECULIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ELOTUZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "EMICIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FILGRASTIM", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "GOLIMUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "INTERFERON ALFA-2A E INTERFERON ALFA-2B", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "IPILIMUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "LIPEGFILGRASTIM", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MEPOLIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "NIVOLUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "OCRELIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "OLARATUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PANITUMUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PEG INTERFERON ALFA-2B", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PEGFILGRASTIM", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PERTUZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RAMUCIRUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RISANQUIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SECUQUINUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TOCILIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VEDOLIZUMABE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30024122": [
    { desc: "VACINA POLIOMIELITE 1 E 3 (ATENUADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA POLIOMIELITE 1, 2 E 3 (INATIVADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30024125": [
    { desc: "VACINA MENINGOCÓCICA ACWY (CONJUGADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA MENINGOCÓCICA C (CONJUGADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30024127": [
    { desc: "VACINA ADSORVIDA DIFTERIA, TÉTANO E PERTUSSIS", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA ADSORVIDA DIFTERIA, TÉTANO E PERTUSSIS (ACELULAR)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA SARAMPO, CAXUMBA, RUBÉOLA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30024129": [
    { desc: "VACINA ADSORVIDA DIFTERIA E TÉTANO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA ADSORVIDA DIFTERIA, TÉTANO, PERTUSSIS, HEPATITE B (RECOMBINANTE) E HAEMOPHILUS INFL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA ADSORVIDA HEPATITE A (INATIVADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA BCG", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA CÓLERA (INATIVADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA COVID-19", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA DENGUE 1, 2, 3 E 4", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA FEBRE AMARELA (ATENUADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA FEBRE TIFÓIDE (POLISSACARÍDICA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA HAEMOPHILUS INFLUENZAE B (CONJUGADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA PAPILOMAVÍRUS HUMANO 6, 11, 16 E 18 (RECOMBINANTE)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA PNEUMOCÓCICA 10-VALENTE (CONJUGADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA PNEUMOCÓCICA 13-VALENTE (CONJUGADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA PNEUMOCÓCICA 23-VALENTE (POLISSACARÍDICA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA RAIVA (INATIVADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA ROTAVÍRUS HUMANO G1P 8 (ATENUADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA SARAMPO, CAXUMBA, RUBÉOLA E VARICELA (ATENUADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VACINA VARICELA (ATENUADA)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30029000": [
    { desc: "Inoculantes, meios de cultura e outros microorganismos para uso agrícola; em conformidade ", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ONASEMNOGENO ABEPARVOVEQUE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042032": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "RIFAMPICINA + ISONIAZIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042059": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CEFALOTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CEFOXITINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CEFTAZIDIMA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042063": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "IDARRUBICINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042069": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CLORIDRATO DE DAUNORRUBICINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE DOXORRUBICINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE IDARRUBICINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042071": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "VANCOMICINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042091": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "MITOMICINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042093": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "SULFATO DE BLEOMICINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042094": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CILASTATINA SÓDICA + IMIPENEM", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042095": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ANFOTERICINA B EM LIPOSSOMAS", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30042099": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ANFOTERICINA B", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE EPIRRUBICINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DOXICICLINA MONOIDRATADA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TETRACICLINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043100": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "INSULINA GLARGINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "INSULINA HUMANA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043210": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACEPONATO DE METILPREDNISOLONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PREDNISOLONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SUCCINATO SÓDICO DE HIDROCORTISONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043220": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ESPIRONOLACTONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043290": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACETATO DE ABIRATERONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DEXAMETASONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043918": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACETATO DE TRIPTORRELINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "EMBONATO DE TRIPTORRELINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TRIPTORRELINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043919": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACETATO DE LEUPRORRELINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043926": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "OCTREOTIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043927": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACETATO DE GOSSERRELINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "GOSSERRELINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043929": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACETATO DE DEGARELIX", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ACETATO DE OCTREOTIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ACETATO DESMOPRESSINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALFATIROTROPINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DIASPARTATO DE PASIREOTIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PAMOATO DE PASIREOTIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SOMATROPINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043936": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACETATO DE MEGESTROL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FULVESTRANTO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043939": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACETATO DE CIPROTERONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ETINILESTRADIOL + LEVONORGESTREL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043994": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "EXEMESTANO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30043999": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "BUDESONIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30044910": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CLORIDRATO DE TOPOTECANA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFATO DE VINCRISTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VIMBLASTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VINCRISTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30044950": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "GRANISETRON", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30044990": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "BROMETO DE IPRATRÓPIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE GRANISSETRONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE IRINOTECANO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE IRINOTECANO TRI-HIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DICLORIDRATO DE QUININA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DITARTARATO DE VINORELBINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "QUININA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFATO DE MORFINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFATO DE MORFINA PENTAIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFATO DE QUININA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TARTARATO DE VINORELBINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VINORELBINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30045010": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "FOLINATO DE CÁLCIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30045090": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ÁCIDO FOLÍNICO (FÓLICO)", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE PIRIDOXINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ISOTRETINOÍNA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30046000": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ARTEMÉTER", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ARTEMÉTER + LUMEFANTRINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ARTESUNATO + CLORIDRATO MEFLOQUINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ARTESUNATO DE SÓDIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049012": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ASPARAGINASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049014": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "IDURSULFASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049019": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ALFA-ALGLICOSIDASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALFAELOSULFASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALFAVESTRONIDASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ALTEPLASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "GALSULFASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PANCREATINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PEGASPARGASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RASBURICASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TENECTEPLASE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049029": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ACITRETINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ANTIMONIAL PENTAVALENTE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FUMARATO DE DIMETILA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049034": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CITRATO DE TAMOXIFENO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TAMOXIFENO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049035": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CARBIDOPA + LEVODOPA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049038": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CLORAMBUCILA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049039": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ÁCIDO TRANEXÂMICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE AMINOLEVULINATO DE METILA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE CINACALCETE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE DOBUTAMINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE FINGOLIMODE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE MITOXANTRONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MESILATO DE RASAGILINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PREGABALINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SUCCINATO DE METOPROLOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049041": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CLORIDRATO DE METOCLOPRAMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049042": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ATENOLOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049043": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "LIDOCAÍNA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049047": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ISETIONATO DE PENTAMIDINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049048": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CARMUSTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MESILATO DE DESFERROXAMINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049049": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "FOSFATO DE OSELTAMIVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MARAVIROQUE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RALTEGRAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TERIFLUNOMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049058": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CLODRONATO DISSÓDICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FOTEMUSTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049059": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ALENDRONATO DE SÓDIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "AMIFOSTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "BICALUTAMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CABAZITAXEL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CITRATO DE IXAZOMIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DAPAGLIFLOZINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DOCETAXEL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DOCETAXEL TRI-HIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "IBANDRONATO SÓDIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MESNA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MICOFENOLATO DE SÓDIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MIFAMURTIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PACLITAXEL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PAMIDRONATO DISSÓDICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SINVASTATINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049063": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "MERCAPTOPURINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PRAZIQUANTEL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049064": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "DIAZEPAM", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049066": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "AZATIOPRINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049068": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "BORTEZOMIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE ERLOTINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DACARBAZINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ENFUVIRTIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FUMARATO DE TENOFOVIR DESOPROXILA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "LETROZOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "LOPINAVIR + RITONAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MESILATO DE IMATINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MESILATO DE NELFINAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "NEVIRAPINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SAQUINAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFATO DE ABACAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFATO DE ATAZANAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFATO DE INDINAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TEMOZOLOMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TENOFOVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TIOGUANINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ZIAGENAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049069": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ABACAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ABEMACICLIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ACALABRUTINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ÁCIDO ZOLEDRÔNICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ANASTROZOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "APALUTAMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "AXITINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "BENZONIDAZOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "BESILATO DE ANLODIPINO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "BRIGATINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLOFAZIMINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE ALFENTANILA MONOIDRATADA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE PALONOSETRONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE PONATINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CRIZOTINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DAROLUTAMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DEFERASIROX", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DICLORIDRATO DE DACLATASVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DICLORIDRATO DE SAPROPTERINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DIFOSFATO DE CLOROQUINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DIMETILSULFÓXIDO DE TRAMETINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ELEXACAFTOR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ELTROMBOPAGUE OLAMINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ENZALUTAMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ERDAFITINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ESILATO DE NINTEDANIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ETOMIDATO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ETRAVIRINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FENTANILA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FLUORURACILA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FOSFATO DE RUXOLITINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FOSFATO DE SITAGLIPTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "GANCICLOVIR SÓDICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "HALOPERIDOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "IBRUTINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "IVACAFTOR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "LEVETIRACETAM", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "LOSARTANA POTÁSSICA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "LUMACAFTOR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MALEATO DE ACALABRUTINIBE MONOIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MALEATO DE SUNITINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MESILATO DE OSIMERTINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "METOTREXATO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "METOTREXATO DE SÓDIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MIDAZOLAM", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "NILOTINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "NITRENDIPINO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "OLAPARIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PALBOCICLIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PEMETREXEDE DISSÓDICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PEMETREXEDE DISSÓDICO HEMIPENTAIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PEMETREXEDE DISSÓDICO HEPTAIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PLERIXAFOR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RABEPRAZOL SÓDICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "REGORAFENIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RILUZOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RISDIPLAM", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RISPERIDONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SACUBITRIL VALSARTANA SÓDICA HIDRATADA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SAXAGLIPTINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SUCCINATO DE RIBOCICLIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFATO DE LAROTRECTINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TARTARATO DE VARENICLINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TEZACAFTOR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TOSILATO DE SORAFENIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "UPADACITINIBE HEMI-HIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VANDETANIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049072": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "SULFADIAZINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SULFAMETOXAZOL + TRIMETROPINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049076": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "FUROSEMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049078": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "APREPITANTO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE GENCITABINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "EFAVIRENZ", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "EMTRICITABINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ENTRICITABINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ENTRICITABINA + FUMARATO TENOFOVIR DESOPROXILA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ETOPOSIDEO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "EVEROLIMO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FOSAMPRENAVIR CÁLCICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "FOSFATO DE FLUDARABINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RITONAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TACROLIMO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TENIPOSIDEO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TENSIROLIMO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TIPRANAVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049079": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "ALPELISIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "AMBRISENTANA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "AZACITIDINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "BARICITINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CAPECITABINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CARFILZOMIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CELECOXIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CICLOFOSFAMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CITARABINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLADRIBINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE ALECTINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE PAZOPANIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORIDRATO DE ZIPRASIDONA MONOIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DASATINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DECITABINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DICLORIDRATO DE PRAMIPEXOL MONOIDRATADO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DIDANOSINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DIMALEATO DE AFATINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DOLUTEGRAVIR SÓDICO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ESTAVUDINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "GEFITINIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "IFOSFAMIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "LAMIVUDINA + ZIDOVUDINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "LINEZOLIDA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MALEATO DE TIMOLOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MESILATO DE DABRAFENIBE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MICOFENOLATO DE MOFETILA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MIDOSTAURINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "NUSINERSENA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PIOGLITAZONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "RIBAVIRINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SELEXIPAGUE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "SOFOSBUVIR", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TAFAMIDIS MEGLUMINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TERIZIDONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "VINFLUNINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ZIDOVUDINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049095": [
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "BUSSULFANO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "DIETILESTILBESTROL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "MITOTANO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "PROPOFOL", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
  "30049099": [
    { desc: "Substitutos de enxerto ósseo", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IV da LC 214/2025" },
    { desc: "Conjuntos de troca e concentrados polieletrolíticos para diálise", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IV da LC 214/2025" },
    { desc: "Vacinas, soros e medicamentos, de uso veterinário, exceto de animais domésticos", reducao: 60, tipo: "Alíquota Zero", anexo: "Anexo IX da LC 214/2025" },
    { desc: "CARBOPLATINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CISPLATINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "CLORETO DE SUXAMETÔNIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ENFLURANO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "GLICOSE", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "HIDROXIUREIA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "HIPOCLORITO DE SÓDIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "ISOFLURANO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "METILPREDNISOLONA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "OXALIPLATINA", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
    { desc: "TRIÓXIDO DE ARSÊNIO", reducao: 100, tipo: "Red. 60%", anexo: "Anexo XIV da LC 214/2025" },
  ],
};
